version: '2'
services:
  consul:
    extends:
        file: base.yml
        service: consul

  ipfs0:
    extends:
        file: base.yml
        service: ipfs
    hostname: ipfs0
    container_name: ipfs0
    links:
     - consul:consul
    ports:
     - "8080:8080"
     - "5001:5001"
     - "4001:4001"

  ipfs1:
    extends:
        file: base.yml
        service: ipfs
    hostname: ipfs1
    container_name: ipfs1
    links:
     - consul:consul

networks:
  ipfs:
    driver: bridge
