consul:
    extends:
        file: base.yml
        service: consul

ipfs0:
    extends:
        file: base.yml
        service: ipfs
    hostname: ipfs0
    container_name: ipfs0
    environment:
     - SUPERVISOR_SKIP_SRV=ipfs
    # - SUPERVISOR_START_EXTERNAL=/opt/qnib/ipfs/bin/startsh
    links:
     - consul:consul
    ports:
     - "8080:8080"
     - "5001:5001"
     - "4001:4001"

ipfs1:
    extends:
        file: base.yml
        service: ipfs
    hostname: ipfs1
    container_name: ipfs1
    environment:
     - SUPERVISOR_SKIP_SRV=ipfs
    # - SUPERVISOR_START_EXTERNAL=/opt/qnib/ipfs/bin/start.sh
    links:
     - consul:consul

  
